#!/usr/bin/env bash

set -e # halt script on error

bundle exec jekyll build

bundle exec htmlproofer \
  --assume-extension \
  --check-html \
  --empty-alt-ignore \
  --report-missing-names \
  --report-script-embeds \
  --url-ignore http://aloverso-htl-lab2.herokuapp.com \
  "$@" \
  ./_site

# --check-external-hash isn't included, because Google doc URL's
# #gid=0 and #bookmark=... don't name anchor locations.
